# Generated by Django 5.0.7 on 2024-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileUrl',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
