# Generated by Django 5.0.7 on 2024-12-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_posts',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='network.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='network.post'),
        ),
    ]
