# Generated by Django 5.0.7 on 2025-01-13 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_following_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
